// Code generated by "stringer -type=Format -linecomment"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Color-0]
	_ = x[Text-1]
	_ = x[Json-2]
}

const _Format_name = "colortextjson"

var _Format_index = [...]uint8{0, 5, 9, 13}

func (i Format) String() string {
	if i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
